{cluster_spec,"single_c200",
 [{cookie,"cookie_single_c200"},
  {dir,"single_c200"},	
  {num_controllers,3},	
  {controller_host_specs,["c200"]},
  {num_workers,20},
  {worker_host_specs,["c200"]}
 ]
}.
